### ISSUE TITLE
Meta Issue: metatensor atomsitic models integration with simulation engines

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/metatensor#648]
This is a meta-issue to serve as a list of the different integrations between metatensor atomistic models and simulation engines. Any longer discussion should be split into a separate issue and linked back here.

### Finished integrations

- [x] Energy calculator for ASE (in this repo)
- [x] Energy calculator for i-PI (https://github.com/i-pi/i-pi/tree/master/examples/clients/metatensor)

### Current prototype integrations

- [ ] Energy calculation in LAMMPS: https://github.com/lammps/lammps/pull/4163
- [ ] Collective variable calculation in PLUMED: https://github.com/plumed/plumed2/pull/1082

### Next integrations/Improvements

- [ ] GROMACS, using https://gitlab.com/gromacs/gromacs/-/issues/5039
- [ ] Bindings to the kokkos version of LAMMPS
- [ ] Computing more than energies in LAMMPS

### Desired integrations

- [ ] OpenMM, maybe using https://github.com/openmm/openmm-torch
- [ ] Tinker-HP already have a very nice API, we could maybe link to it (although it seems to go through Python): https://github.com/TinkerTools/tinker-hp/blob/master/GPU/Deep-HP.md
- [ ] CP2K: we need to look into how we can do this

**Comment by PicoCentauri** [comment]
> CP2K: we need to look into how we can do this

FORTRAAAAAN ❤️

Cool, we might also want to add [espresso](https://espressomd.org) since they seemed interested.
